### ISSUE TITLE
boot.ipxe add special retry fields

### ISSUE THREAD

**Issue by JulienBalestra** [coreos/matchbox#369]
I use PXE chain loading to bootcfg iPXE endpoint (`http://bootcfg/boot.ipxe`)

This provide to my machines the following iPXE script:

```
#!ipxe
chain ipxe?uuid=${uuid}&mac=${net0/mac:hexhyp}&domain=${domain}&hostname=${hostname}&serial=${serial}
```

With this iPXE configuration I get some ipxe error 0x040ee119 who lead me to this [iPXE page](http://ipxe.org/err/040ee1)

So I'd like to introduce some infinite loop in the DHCP process like:

```
#!ipxe
:retry_dhcp
dhcp || goto retry_dhcp
```

Is it something possible ? 
Is it also possible to do the same in the `http://bootcfg/ipxe?<selector>=<value>` field ?

**Comment by dghubble** [comment]
I don't think its possible at the moment, the ipxe config given is rather fixed. Would be fixed by #92

**Comment by jhart99** [comment]
I know that this issue is a little old, but I can tell you I've run across the same issue and have a partial solution.  You don't need to point to the ipxe endpoint.  Instead you can add an ipxe script to assets which can give you the little extras you want and then at the end you can chain load the ipxe endpoint.

For example, make a file containing the following and add it to assets/dhcp.ipxe:
```
#!ipxe
:retry_dhcp
dhcp || goto retry_dhcp
chain ../boot.ipxe
```

And now point the machine loading with PXE to this file instead.  If you were looking at the dnsmasq examples, it would just change http://matchbox.foo:8080/boot.ipxe to http://matchbox.foo:8080/assets/dhcp.ipxe .  By chainloading you will still have the DHCP address through all the steps so it will be configured when it loads /boot.ipxe as well as /ipxe?...

**Comment by JulienBalestra** [comment]
Thank you @jhart99 for your idea.

I made a custom API in front of matchbox: this solve some problems and add more control for my use-case.
