### ISSUE TITLE
Are there any similar tools or libraries ?

### ISSUE THREAD

**Issue by AmitKumarDas** [coreos/matchbox#419]
Hi Team,

I am experimenting using coreos-baremetal library for installation, upgrades, etc to manage [openebs](https://github.com/openebs) infrastructure. Are there any blogs etc that talk about this project ?

Few other queries:
- How does coreos-baremetal relate to Hashicorp's Terraform ?
- Is coreos-baremetal similar to Docker's Infrakit in spirit ?

**Comment by dghubble** [comment]
### About

matchbox (we're going through a rename) is an HTTP/gRPC service for serving machine configs to machines by matching labels (e.g. MAC, uuid, stage, region). It has a read-only API for machines which are PXE booting and a read-write TLS-auth'd gRPC API for building rich dashboards, wizards, and tools which update those machine configs. That's about it.

An example machine config might be a kickstart file. In the case of CoreOS, the machine config is Ignition. Its a pre-boot provisioning system which is very powerful and first-boot only (by design).

The best example of this use at the moment is probably this Tectonic [doc](https://tectonic.com/enterprise/docs/latest/install/bare-metal/index.html). `matchbox` (formerly `bootcfg`) is run as a binary, rkt, docker, or pod on some server and passively serves configs. The Tectonic Installer graphical app helps users create clusters.

`matchbox` is designed for bare-metal first and foremost and is also in use on Linux virtualization platforms (ESX, UCS, QEMU/KVM, etc.) and in Tectonic bare-metal setups on-site.

### Comparison

Terraform is more of a platform for describing all of your infrastructure of all kinds and then executing plugins to maintain that state over time. Terraform is closer to a full configuration management system. By comparison, matchbox is a PXE server with a modern API. If the two were to interact, matchbox would have a matchbox-provider plugin that Terraform uses.

I'm not particularly familiar with InfraKit. The two do not appear similar to me. Infrakit seems to have broad scope and is concerned with leader election, cattle, orchestration, etc. You might ask them what is in-scope and how it compares with Kubernetes or Zookeeper or other systems.

By contrast, `matchbox` is just for provisioning your machines, especially CoreOS machines. Its a glorified way to PXE boot with an Ignition file. From there, whether you install Kubernetes, Mesos, or a highly available kitten picture server with systemd units is up to you.

**Comment by devurandom** [comment]
> If the two were to interact, matchbox would have a matchbox-provider plugin that Terraform uses.

Do you know of an effort to build this?

I assume the end result would be a Terraform Matchbox "provider" that takes the matchbox URL and credentials and offers the ability to create CoreOS "resource" based on e.g. a MAC address? Then one would need an Ignition "provisioner" and teach the Matchbox and other "provider"s how to utilise that (Matchbox: built-in for CoreOS, others: execute cmd xyz)?

**Comment by dghubble** [comment]
@AmitKumarDas To followup, with matchbox v0.6.0, there is support for the https://github.com/coreos/terraform-provider-matchbox and a tutorial using it https://github.com/coreos/matchbox/blob/master/Documentation/getting-started.md
