### ISSUE TITLE
etcd-install

### ISSUE THREAD

**Issue by khanattlab** [coreos/matchbox#430]
How is the etcd-install example supposed to work for the 3 nodes? What does the "os: installed"  for the selector section do. It seems to mess up the URLs if I leave it in there for IPXE boot and without it, its just an etcd cluster in RAM.

**Comment by dghubble** [comment]
Ignition is used to provision CoreOS nodes on first boot from disk. As a special case, Ignition is run on PXE boot with an Ignition config rendered from [install-reboot.json](https://github.com/coreos/matchbox/blob/master/examples/ignition/install-reboot.yaml#L23). That Ignition config has a simple systemd service which pulls the Ignition config to be used on disk boot and performs the install to disk. On first boot from disk, nodes are provisioned into etcd nodes.

There is no further interaction with the matchbox service. On reboots, Ignition is not run again. Re-PXE the machine (IPMI) if you wish to re-provision it into something else. You can learn more in the matchbox docs or by reading about the [machine lifecycle](https://github.com/coreos/matchbox/blob/master/Documentation/machine-lifecycle.md).

**Comment by khanattlab** [comment]
Thanks- so the install to disk should pull the ignition for node1, node2 for a particular selector if the node jsons are in the groups folder and the first boot from disk should have etcd node configuration based on the node json? I will try it again. thanks again.

**Comment by khanattlab** [comment]
OK - get the idea. Somehow the install ignition wasnt picking up the etcd node config properly ( I am thinking the curl command looking for "os": "installed"   so I am going to combine the 2 and try it. thanks

**Comment by khanattlab** [comment]
Got it working although errors on etcd2 service start. Will troubleshoot. @dghubble thanks for the help

**Comment by khanattlab** [comment]
OK - reopening this.  etcd will not start with the new disk installed server. error: "member xxx is already bootstrapped".  I can manually make changes but that defeats the whole purpose. Any changes I can make to the files for etcd to start after install? thanks

**Comment by khanattlab** [comment]
Could it be that I did not add the proxy.json to the groups directory?

**Comment by dghubble** [comment]
If you provision a 3 node etcd cluster and later re-provision one of the nodes, it will not be allowed to join the other two automatically and etcd2 will show an error like "member xxx is already bootstrapped". The old etcd node and freshly installed new etcd node are different. Either provision a fresh cluster or manually register the new node into the existing cluster. This is a data safety aspect of running etcd clusters, its not related to matchbox or etcd proxies.

You shouldn't run into this following the local QEMU/KVM examples/tutorials for matchbox. Since matchox can be used to setup CoreOS clusters which provision anything you like (etcd, Kubernetes, hello world, mesos), you'll want to check the upstream docs (https://coreos.com/etcd/docs/latest/) or systemd examples for running particular services.

**Comment by khanattlab** [comment]
Got it- thanks - and I did get it working---really cool!  @dghubble appreciate the help.

**Comment by dghubble** [comment]
Nice!. Updated title for easier googling.
