### ISSUE TITLE
High Availability Kubernetes Deployment

### ISSUE THREAD

**Issue by danehans** [coreos/matchbox#473]
I have completed a HA Kubernetes deployment using keepalived/nginx. Let me know if you would like me send a PR to document and share my example group, profile and ignition templates.

**Comment by dghubble** [comment]
Tectonic Bare-Metal serves as the production example of how to deploy multi-etcd and multi-controller clusters, do rolling upgrades, etc. In fact, Tectonic clusters developed directly from the examples here so they can be extended to deploy multi-etcd and multi-controller, do rolling upgrades, etc. with only a bit of effort. So if we add an example, it would probably be based on that.

I opened #398 to gauge interest in seeing open-source examples of CoreOS-style multi-controller Kubernetes clusters.

It might be interesting to get a high level description of your approaches though? Or how it differs from Tectonic? keepalived would probably be considered an environment specific detail left as an exercise for the user in our context.

**Comment by danehans** [comment]
@dghubble thanks for the feedback. I have seen the Tectonic BM guide, but never tried it. I created an OpenStack HA [guide](http://docwiki.cisco.com/wiki/OpenStack_Havana_Release:_High-Availability_Manual_Deployment_Guide) back in the day that was well received by the community. I was thinking of doing something similar for Kubernetes. IMO tons of docs exist, but I can't find one end-to-end guide that can be used for a production-style deployment. Here are a few aspects to my approach:

1. I use 3 dedicated etcd3 nodes instead of running etcd2 on controllers. It's my understanding that running a dedicated etcd cluster is a best practice. If that is not the case, please let me know and I'll update my setup.

2. I use a pair of load-balancer nodes that run nginx and keepalived to provide HA to the k8s api's. The nginx load-balancer is configured to terminate SSL and proxy SSL to the backend k8s-controller nodes. In the future, I plan on performing http inspection before proxying https to the k8s api backend.

3. I use multiple network interfaces on nodes to separate public and private traffic. I have one example of bonding 2 physical interfaces and using VLAN segmentation and another example for separate physical interfaces. I have the associated network configurations for both examples. I use the /ipxe endpoint to provision an OS to the network switches. I am also working on adding either ignition or cloud-init support to the network switches to deliver the switch configs.

4. I use [kube-parrot](https://github.com/sapcc/kube-parrot/), BGP on the network switches and [ExternalIPs](https://kubernetes.io/docs/concepts/services-networking/service/#external-ips) to provide external access to k8s services.

For more details, check out my [commits](https://github.com/danehans/matchbox/commits/lab_wip)

**Comment by dghubble** [comment]
Its awesome you've been able to adapt the Container Linux configs from the examples for your use cases! That's exactly the goal!

I think these commits are too specialized to be included directly though. I'd like Matchbox examples to achieve a few high level goals:

* Demonstrate how to provision standard or popular clusters (e.g. vanilla self-hosted bootkube) on Container Linux.
* Keep examples simple. Matchbox's main aim is to be a useful on-premise service/API. That means it won't show every customization or try to compete with specialized tools.
* Keep examples educational. Being able to start with one of the examples is an entrypoint for people learning best-practices and getting excited about Container Linux, matchbox, or Kubernetes.
* Run in the QEMU/KVM development and CI environment (the matchbox service is developed by PXE booting clusters on our laptops and automated by CI).

Your questions:

1. etcd usually recommends dedicated nodes, though lots of those docs assume cloud VMs. To keep the Kubernetes examples simple and usable locally, controllers act as etcd peers. This is going to change once etcd is self-hosted (run as pods). Examples also have a stand-alone etcd3 cluster. The right solution depends on user's needs.
2. Tectonic fronts multiple controllers via DNS round robbin by default and leave it as an exercise for deployers since there are so many ways to do it.
3. Bonded NIC examples might be a useful addition to Container Linux Config docs since its a feature directly exposed through Ignition. VLAN doesn't fit into the development environment, but could be an addition to Container Linux Config docs as well perhaps.
4. BGP might be a useful topic for a tutorial in docs. To expose services externally and perform TLS termination, you could use Kubernetes Ingress controllers and no external components are needed. This was put in Tectonic. It can be integrated with BGP with some work.

Other comments:
* I've avoided hardcoding IPs into any cluster examples. I'd prefer machine configurations use DNS names so its easier to reconfigure the network within breaking things later.
* You might wish to explore self-hosted Kubernetes sooner rather than later. Its the one we're most actively developing, testing, iterating on, and integrating into the enterprise offerings too. Self-hosted etcd, etcd3, self-hosted flannel, and operators are being developed for self-hosted Kubernetes (i.e. bootkube).

**Comment by bzub** [comment]
I use BGP to route Virtual IPs, for HA purposes. Deployment is entirely Bootkube and Matchbox based.  It strays from the examples in that it uses Calico and not Flannel.

Would a Calico example of Bootkube be of interest? Otherwise I'm sure I could achieve the same thing with GoBGP services managed by systemd or kubernetes.

**Comment by danehans** [comment]
@bzub can you expand on:

> I use BGP to route Virtual IPs, for HA purposes.

Are these virtual IP's of endpoints such as kube-apiserver and/or etcd? I am interested in better understanding your use of BGP.

I am currently in the process of converting my matchbox-based deployment from Flannel to Calico. I would really appreciate you sharing your cloud-init or ignition templates.

**Comment by bzub** [comment]
@danehans 

My Calico + Bootkube setup is documented in a [Bootkube issue](https://github.com/kubernetes-incubator/bootkube/issues/407#issuecomment-292057747) for now.  Outside of the VIPs, it doesn't really touch my Container Linux Config or matchbox, which in this context just deploys Bootkube per the examples since I manually replace the Flannel manifests that Bootkube renders with Calico ones.

The virtual IPs can be used for most any service in a Kubernetes cluster.  The ways I expose them in Kubernetes are:
- nginx-ingress listening on the VIPs via `externalIPs`
- Using `externalIPs` directly in a service without a reverse proxy in front

You could also use `hostNetworking` at the Pod level to bypass kube-proxy, which may help simplify the preservation of source IPs if desired.  To answer your question I don't actually use this for kube-apiserver or etcd yet, but only because I haven't had time to make the change from a DNS round-robin approach to HA for those services.  For kube-apiserver it should only be a matter of configuring kube-apiserver to use a VIP via the `--bind-address=` argument, and in my case adding a new VIP for that role since nginx-proxy would conflict with kube-apiserver's use of port 443.  In fact for now I use `--bind-address` to bind to the node's non-VIP, otherwise it tries to use all interfaces including the VIP.  Currently I use the VIPs for external DNS and all my personal services I want exposed outside the cluster.

I put more details and examples of the Matchbox/CL Config/Calico setup [in a gist](https://gist.github.com/bzub/7d29de52b57a272d1fffcad8f1cc490d).  I'll try to improve it with inline links to documentation as I find time, feel free to comment.  I'll also make all my files public in full at some point and let you know.  I should point out that this setup requires a router or switch that talks BGP and to have Calico peer with it.  Not difficult, but I would like to move in your direction @danehans and use Linux servers + Kubernetes services for networking instead.

**Comment by dghubble** [comment]
A simple multi-controller Kubernetes example was added in
https://github.com/coreos/matchbox/tree/master/examples/terraform/bootkube-install#options via `multi-controller.tfvars.example`. The design flexibly takes a list of controllers and workers, so the multi-controller example just shows how to list 3 controllers and 1 worker (instead of the usual 1 controller, 2 workers in examples). The controller DNS record (i.e. `k8s_domain_name`) refers to controllers in a round-robin fashion, instead of just to a single controller.

Ingress controllers are certainly important for HA application serving and more custom networking (Calico, BGP, VIPs, etc.) is certainly relevant for many deployment scenarios. But probably out of scope for these matchbox examples showing how different clusters can be provisioned on-prem.
