### ISSUE TITLE
Question: Differences between "self-hosted" and "static" kubernetes cluster

### ISSUE THREAD

**Issue by styxlab** [coreos/matchbox#512]
Could you please clarify the differences between the [self-hosted](https://github.com/coreos/matchbox/blob/master/Documentation/bootkube.md) multi-node kubernetes cluster and the [static](https://github.com/coreos/matchbox/blob/master/Documentation/kubernetes.md) multi-node kubernetes cluster?  As the "self-hosted" version has been updated more frequently lately, I'd like to know whether:

1. the "static" version will be replaced by the "self-hosted" version in the future?
2. the "static" version will be updated to kubernetes version `v1.6.2` anytime soon?
3. the "static" version will be updated to use `etcd3`?
4. why does the "self-hosted" version not need `flannel` anymore?

I'd really appreciate some insight into the maintenance and future directions of both versions.

**Comment by dghubble** [comment]
Sure, great question!

CoreOS has [coreos-kubernetes](https://github.com/coreos/coreos-kubernetes) to show how to create "static" Kubernetes clusters and [bootkube](https://github.com/kubernetes-incubator/bootkube) to create "self-hosted" Kubernetes clusters.

### Technical

In a nutshell, static Kubernetes runs control plane components as systemd services on the host. Its simple to reason about and the repo has educational docs, but in practice its fairly static (hard to re-configure). Self-hosted Kubernetes runs control plane components as pods. A one-time bootstrapping process is done to setup that control plane. Configuring hosts becomes much more minimal, requiring only a running Kubelet. This favors performing rolling upgrades through Kubernetes, the cluster system, and provisioning immutable host infrastructure. A node's only job is to be a "dumb" member of the larger cluster.

You can read the full doc (much better than my summary) at https://github.com/kubernetes/community/blob/master/contributors/design-proposals/self-hosted-kubernetes.md

### Future

Lots of development effort focuses on self-hosted Kubernetes as the way forward. Flannel is used in self-hosted, but its launched as a daemonset as part of bootstrapping. The etcd team is also working to support etcd running as pods atop self-hosted Kubernetes so that a statically configured etcd cluster doesn't need to be setup on hosts. Tectonic clusters (CoreOS's Enterprise offering) are also self-hosted across supported platforms (bare-metal, AWS, etc.) and kubeadm is getting self-hosted support.

I'd encourage newcomers to choose the "self-hosted" Kubernetes approach. There is a [tutorial](https://github.com/coreos/matchbox/tree/master/examples/terraform/bootkube-install) for deploying a self-hosted Kubernetes cluster on bare-metal or enterprise folks can try the [Tectonic installer](https://github.com/coreos/tectonic-installer).

### QA

Yes, I expect "self-hosted" Kubernetes to increasingly just be called "Kubernetes". Its the same Kubernetes, just embracing the idea that components benefit from Kubernetes primitives and being managed by speaking to the cluster, not editing hosts.

The team is still discussing how static Kubernetes will be maintained. coreos-kubernetes examples are the upstream for that cluster example, so matchbox will follow their for lead if there is an update or wind down. You may wish to ask there directly.

**Comment by styxlab** [comment]
Thanks a lot for your prompt and detailed answer. I have been running the static Kubernetes cluster for some time, but will give the "self-hosted" variant a shot soon.

**Comment by dghubble** [comment]
Great, feel welcome to open issues if you have difficulties. I'll try to update this if there are any concrete plans for static Kubernetes.
