### ISSUE TITLE
get-coreos use of Version variable seems overly specific

### ISSUE THREAD

**Issue by brianredbeard** [coreos/matchbox#526]
In looking through [`scripts/get-coreos`](https://github.com/coreos/matchbox/blob/75e428aece87dd72cb891670534ed4ae6a5c56ca/scripts/get-coreos#L9) I see that the variable `Version` is being set, which seems odd (and add an additional maintenance burden for this utility).

In other CoreOS utilities we leverage the file `version.txt` which currently exists in all of the Container Linux asset directories.  As an example:

https://github.com/coreos/scripts/blob/ea0e8fd5833d28854a6ed278ddae85d24505c802/oem/generic/check_etag.sh

https://github.com/coreos/scripts/blob/ea0e8fd5833d28854a6ed278ddae85d24505c802/oem/openstack/glance_load.sh#L59-L63

In these examples we leverage the fact that the file `version.txt` always exists, is always small, and will provide useful variables like `COREOS_VERSION` for a release channels (e.g. it can be consumed as: `"https://${CHANNEL}.release.core-os.net/${BOARD}/current"`) thus greatly simplifying retrieval and ensuring that this works across platforms (e.g. beyond AMD64).

**Comment by dghubble** [comment]
The `get-coreos` script downloads the raw and pxe images for a specified version of Container Linux which is handy for users choosing to populate the matchbox assets cache (as opposed to PXEing and installing from the public images). It is used like:

```
./scripts/get-coreos stable 1353.7.0
```

It accepts the desired version because example clusters are validated against a specific version of Container Linux for determinism. *However*, if you do wish to download the "latest" version from a channel (and override the last cache download), you can use `./scripts/get-coreos stable current`. Alternately, images can be downloaded however you prefer, its just a helper script.

With that context in mind, is there a specific problem I can help solve?

**Comment by dghubble** [comment]
ping ^

**Comment by dghubble** [comment]
Any update or can this be closed?

**Comment by dghubble** [comment]
Closing for now. Feel free to re-open if there is a specific change we should make.
