### ISSUE TITLE
Build keeps failing with missing kubernetes directory

### ISSUE THREAD

**Issue by pfischer8989** [coreos/matchbox#639]
module.cluster.null_resource.copy-secrets.0: Provisioning with 'file'...
module.cluster.null_resource.copy-secrets.0: Provisioning with 'file'...
module.cluster.null_resource.copy-secrets.0: Provisioning with 'file'...
module.cluster.null_resource.copy-secrets.0: Provisioning with 'file'...
module.cluster.null_resource.copy-secrets.0: Provisioning with 'file'...
module.cluster.null_resource.copy-secrets.0: Provisioning with 'file'...
module.cluster.null_resource.copy-secrets.0: Provisioning with 'file'...
module.cluster.null_resource.copy-secrets.0: Provisioning with 'file'...
module.cluster.null_resource.copy-secrets.0: Provisioning with 'remote-exec'...
module.cluster.null_resource.copy-secrets.0 (remote-exec): Connecting to remote host via SSH...
module.cluster.null_resource.copy-secrets.0 (remote-exec):   Host: cnfc4cnfi01.cnfilab.local
module.cluster.null_resource.copy-secrets.0 (remote-exec):   User: core
module.cluster.null_resource.copy-secrets.0 (remote-exec):   Password: false
module.cluster.null_resource.copy-secrets.0 (remote-exec):   Private key: true
module.cluster.null_resource.copy-secrets.0 (remote-exec):   SSH Agent: false
module.cluster.null_resource.copy-secrets.0 (remote-exec): Connected!
module.cluster.null_resource.copy-secrets.0 (remote-exec): mv: cannot move '/home/core/kubeconfig' to '/etc/kubernetes/kubeconfig': No such file or directory
^CInterrupt received.

I can't seem to get around this one. It cannot copy over the kubeconfig because the directory has not been created yet. I think this directory gets created from the bootkube template files but it seems this keeps running before it happens. Is there a way to control the order that terraform or matchbox runs these files? 

I will say that sometimes this does work and after the second boot of the server it successfully completes. But i have now tried it 8 times with this error happening every time.

**Comment by dghubble** [comment]
Journal the matchbox logs. You're most likely in a boot loop where your machines are getting the container-linux-install profile over and over again. You should be sure to configure the machines to boot from disk via BIOS or IPMI.

You can debug by SSHing to a node - if its using container-linux-install profile, you'll find an `installer.service` running and no `kubelet.service`.

**Comment by dghubble** [comment]
Also, note https://github.com/coreos/matchbox/tree/master/examples/terraform/bootkube-install#apply. Terraform apply will show the errors you're seeing when trying to copy to a machine which hasn't yet finished its disk install and first boot from disk. You'll have to run `terraform apply` until it successfully reconciles.

There is a dirty hack to trick terraform into not being able to SSH to the node during the install phase (add the pubkey to a user called something other than "core"). I added this to Tectonic since its mostly a UI based flow, but I don't want to add it here. The crux of the issue is that Terraform doesn't seem to have a way to gate a remote_exec behavior based on some sentinel or condition like doing a disk install. Perhaps we make the error better "Cannot move file, this machine is still installing and isn't ready yet".

**Comment by pfischer8989** [comment]
Yeah the failing on the first time is expected as you say it is still installing continer-linux. It is when it comes up again and it still fails that is perplexing. The installer.service has completed and is no longer there. Etcd is running in rkt properly and has added the other nodes ( I am using the etcd3 cluster tf files ).

But it does not seem to start the boootkube process properly. There is no kubelet service running on the master....in fact no kubernetes stuff at all.....aside from the kubeconfig being copied into /home/core

Does it try to install all three and make sure etcd is running before it moves onto kubernetes stuff? like in the master i am seeing the raft algorithm trying to add the other hosts for instance....

**Comment by pfischer8989** [comment]
Scratch that last part. Etcd3 works fine...once the other servers come up they are added and etcd3 is up and running. 

But when you re-run terraform apply once all three nodes are up it runs the ssh copy script and fails on the kubernetes part because the directory does not exists yet. So it seems that the ssh stuff is running before bootkube is run and able to create those directories.

**Comment by dghubble** [comment]
> Does it try to install all three and make sure etcd is running before it moves onto kubernetes

An Ignition config declares the desired state of the disk (systemd units, files, etc.). It is not an script / imperative style except that the final part is that Terraform must be used to distribute secrets and call sudo systemctl start bootkube.

**Comment by dghubble** [comment]
Controllers use the following Container Linux config: https://github.com/coreos/matchbox/blob/master/examples/terraform/modules/profiles/cl/bootkube-controller.yaml.tmpl

The `/etc/kubernetes` directory should exist the moment you're able to access the machine.This is because a `/etc/kubenetes/kubelet.env` file is created during disk provisioning. https://github.com/coreos/matchbox/blob/master/examples/terraform/modules/profiles/cl/bootkube-controller.yaml.tmpl#L125

**Comment by pfischer8989** [comment]
ok well then something is not working with the initial install then. There is no kubernetes systemd files or bootkube on the target servers and no kubernetes directory or kubelet.env file either.

Will dig through the terraform.log to see if i can find anything about this

**Comment by dghubble** [comment]
Have these Container Linux machines been used for something previously or have disks been shuffled maybe? I've gotten myself in scenarios where there are multiple disks labeled root and by default the examples install to whichever is `/dev/sda`. https://github.com/coreos/matchbox/issues/579

You can also look at the Container Linux config for the machine directly by visiting:

```
http://matchbox.example.com:8080/ignition?mac=52:54:00:a1:9c:ae&os=installed
```

assuming you substitute in your real hostname, port, and MAC address (and haven't switched to some different machine matching strategy)

**Comment by dghubble** [comment]
The way the examples are written currently, it may be possible that fetching that config during installs fails and just a plain Container Linux install occurs, without any Ignition config. https://github.com/coreos/matchbox/blob/master/examples/terraform/modules/profiles/cl/container-linux-install.yaml.tmpl#L23

During install on a node you might journal installer.service and make sure it gets a config. If not, we need to fix that.

```
journalctl -f -u installer
cat ignition.json
```

**Comment by pfischer8989** [comment]
ok so this:

http://matchbox.example.com:8080/ignition?mac=52:54:00:a1:9c:ae&os=installed

does not even list any of the kubernetes stuff. Here is the output for my server:

{"ignition":{"version":"2.0.0","config":{}},"storage":{},"systemd":{"units":[{"name":"etcd-member.service","enable":true,"dropins":[{"name":"40-etcd-cluster.conf","contents":"[Service]\nEnvironment=\"ETCD_IMAGE_TAG=v3.2.0\"\nEnvironment=\"ETCD_NAME=cnfc4cnfi01\"\nEnvironment=\"ETCD_ADVERTISE_CLIENT_URLS=http://cnfc4cnfi01.cnfilab.local:2379\"\nEnvironment=\"ETCD_INITIAL_ADVERTISE_PEER_URLS=http://cnfc4cnfi01.cnfilab.local:2380\"\nEnvironment=\"ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379\"\nEnvironment=\"ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380\"\nEnvironment=\"ETCD_INITIAL_CLUSTER=cnfc4cnfi01=http://cnfc4cnfi01.cnfilab.local:2380,cnfc4cnfi02=http://cnfc4cnfi02.cnfilab.local:2380,cnfc4cnfi03=http://cnfc4cnfi03.cnfilab.local:2380\"\nEnvironment=\"ETCD_STRICT_RECONFIG_CHECK=true\"\n"}]},{"name":"locksmithd.service","dropins":[{"name":"40-etcd-lock.conf","contents":"[Service]\nEnvironment=\"REBOOT_STRATEGY=etcd-lock\"\n"}]}]},"networkd":{},"passwd":{"users":[{"name":"core","sshAuthorizedKeys":[""]}]}}

took my key out. 

I basically added the etcd cluster tf to the bootkube example and it just seems to ignore all the bootkube files. 

and to answer your other question yes they have been installed with other things before. Some redhat atomic servers

this also does not list anything on the installed node. 

journalctl -f -u installer

localhost core # journalctl -f -u installer
-- Logs begin at Mon 2017-08-14 18:44:34 UTC. --

**Comment by dghubble** [comment]
Ok, this shows its not related to previous installs or complex disk mixups like I mentioned. Sounds like the machines are provisioned according to the config they're being served (i.e. just an etcd-member.service and SSH public key).

For clarity, you're following the Terraform-based `bootkube-install` example right? The one described here:  https://github.com/coreos/matchbox/tree/master/examples/terraform/bootkube-install?

If Matchbox is matching the machine to config that isn't what you expect, its because there is ambiguity in the configuration. The most common way this can happen is if you use terraform to create on cluster (say with the `etcd3` example), don't run `terraform destroy` or remove those configs, and then terraform apply a different example.  At that point, the machine with MAC 52:54:00:a1:9c:ae is mapped to two different profiles. Depending on how you deployed matchbox (binary, container, kubernetes), check the contents of `/var/lib/matchbox/groups` or your terraform configs to see if multiple entries are matching that mac. Or if you don't care about if you don't care about the state, delete it and go through the `bootkube-install` example anew.

At least, that's my best guess at what you're seeing.

**Comment by pfischer8989** [comment]
ok i think i see what is happening. To answer your question yes i am using the bootkube-install but i have added in the etcd3.tf from the etcd3-install in as well. I was doing this because i wanted kubernetes installed to a distributed etcd3 cluster just one of them. What i did not realize until you pointed it out was it was created container-linux files in the groups directory. this explains why it never hit the boot-kube container-linux files.

So it looks like i will have to either remove those portions from the etcd.tf or port the specific etcd3 config into the cluster.tf. Any recommendation here?

As always thanks for all your help!

**Comment by dghubble** [comment]
Ok, that explains what you're seeing. The 3-node etcd cluster example (etcd3-install) and Kubernetes cluster example (bootkube-install) are separate. As is, you're telling node1 to match to the etcd3 profile *and* to match to the bootkube-controller profile, etc. They must match to one only. I should have clarified which example and any mods from the beginning.

Now, the bootkube-install will provision controllers as etcd peers out of the box - if there is one controller, its a one-node etcd. If there are three controllers - its a 3-node etcd. Its the default I use and recommend. It sounds like you're wanting a Kubernetes cluster with a separate standalone etcd cluster? If so, that's a different architecture - you'd need to change the control plane to point to that and self-hosted etcd wouldn't be an option. You'd go from having 2 kinds of machine profiles to 3 (etcd, controller, worker) and need to restructure the bootkube Terraform module to support that.

**Comment by pfischer8989** [comment]
Ok perfect so i will try the multi-controller version ( i was using the single controller version ) Did not know it did all three in an etcd cluster but of course that makes sense =o)

**Comment by dghubble** [comment]
Cool
